### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by alevin1** [Petschko/Java-RPG-Maker-MV-Decrypter#12]
Stuck at the JAR stage. What do I JAR? How do I JAR?

I have tried zipping everything and using a JAR converter.

**Comment by Petschko** [comment]
Hey what's the problem in the first place?

I guess you want to launch the Program? You can find the compiled Program here: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/releases/tag/v0.1.3-alpha (Newest Version)

Just unpack that and use the "start(.bat)" File. Make sure that you have installed Java

**Comment by alevin1** [comment]
Hi,
Hope you're well. The Decrypter seems to have stopped decrypting files?

On Wed, Dec 20, 2017 at 11:39 AM, Peter Dragicevic <notifications@github.com

**Comment by Petschko** [comment]
Hello,

please provide more details else I can't help you
