### ISSUE TITLE
A game file cannot be decrypt

### ISSUE THREAD

**Issue by Flagred** [Petschko/Java-RPG-Maker-MV-Decrypter#17]
Stranger of power 2 cannot be decrypt and when it decrypt it is nothing inside the output. Please do fix that. I no sure if i do anything wrong or no but you can test self if you free.

**Comment by Petschko** [comment]
It's not a bug, the creator of the game is just so mad, he think if he hide the key somewhere else it would help, see my step by step instruction to get the Key:
https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/19

If you still have troubles you can send me the game and I analyse it
