### ISSUE TITLE
how to open a RPG-maker MV PROJECT?

### ISSUE THREAD

**Issue by HinagikuKatsura** [Petschko/Java-RPG-Maker-MV-Decrypter#23]
I followe the guide to open a RPG-maker MV PROJECT and choose the Main-Directory,but nothing happened. no warning ,no alert,
please tell me why?And my java version is 14.0.1 .

**Comment by RedAISkye** [comment]
Step 1. Click the menu option "File".
Step 2. Click the submenu option "Select RPG MV Project..."
Step 3. Navigate to the base directory of the game folder that contains subfolders like "www", "locales", "swiftshader" and click Open.
Step 4. Wait for few seconds and this message should appear: "RPG-Maker Project loaded... Please use 'Decrypt -> All' Files to Decrypt."
Step 5. Click "Ok" then do what the message stated and if it finds the decryption key, it will extract all game files to the output directory.

**Comment by Petschko** [comment]
Please note we only support LTS Java-Versions (14 isn't LTS)

https://www.azul.com/files/Java-SE-Lifecycle-131-1024x576.jpg
