### ISSUE TITLE
there is no "set encryption key" button

### ISSUE THREAD

**Issue by badflower-la** [Petschko/Java-RPG-Maker-MV-Decrypter#32]
![image](https://user-images.githubusercontent.com/69483795/116574901-d7cf6500-a916-11eb-8092-d5dcb063b7b3.png)

how

**Comment by Petschko** [comment]
Oh sorry that was a small bug in the release, thats already fixed, i just should roll out the release

It will be rolled out in the next release, I forgot i had it in that exact version... Sorry, I think I will roll it out this weekend or even today when i get the time
