### ISSUE TITLE
Add "Open Current Dir" & "Open Current Dir & encrypt"  & "Open Current Dir & decrypt" 

### ISSUE THREAD

**Issue by TalosDx** [Petschko/Java-RPG-Maker-MV-Decrypter#34]
Pls Add buttons "Open Current Dir" & "Open Current Dir & Decrypt" it would make moddev & gamedev easier.

**Comment by Petschko** [comment]
Hey!

I'm open for improvement, but I'm not entirely sure what you want. Can you please describe what the "Open current Dir" button should do?

Which current directory should it open?

The "Open Current Dir & Decrypt" should just do the same as the first button, just decrypt right away right?

**Comment by TalosDx** [comment]
The current directory is the directory where the Executable File is located
Or console mode like
```
java -jar someJar.jar -decrypt .
java -jar someJar.jar  -encrypt .
java -jar someJar.jar  -encrypt /home/userName/games/myBestGameEver/
```

Where '.' works like in linux

**Comment by Petschko** [comment]
Ah I understand! Thats a neat idea

**Comment by Petschko** [comment]
This will be released in the new Version (Today/Tomorrow)
