### ISSUE TITLE
Add Re-Encrypt-Files-Option

### ISSUE THREAD

**Issue by Petschko** [Petschko/Java-RPG-Maker-MV-Decrypter#4]
This can may usefull for translaters, who want decrypt the files to translate content on them but provide them in the translated version of the game. (The game still looks for the encrypted files, while running)
Please ask the origin creator before

**Comment by Petschko** [comment]
Partial supported now via Command-Line

**Comment by Gfurst** [comment]
Hello, just wanted to ask if you gonna put this up mainstream, as an option on the GUI, or at least describe a way through the GUI. Thank you

**Comment by Petschko** [comment]
Oh I build that, but it seems I didnt pushed it to the master branch yet, should do soon!

**Comment by Petschko** [comment]
This will be added in the next release (Today/Tomorrow). It's already done, I just do some testing
