### ISSUE TITLE
Can't select files in the GUI

### ISSUE THREAD

**Issue by Gfurst** [Petschko/Java-RPG-Maker-MV-Decrypter#42]
Currently, using on linux, the Java GUI, I can't select any of the files at all. However it does work fine for extracting everything at once.

**Comment by Petschko** [comment]
Thats correct, its not implemented yet.

**Comment by Petschko** [comment]
You get updates about this here in the future: https://gitlab.com/Petschko/Java-RPG-Maker-MV-Decrypter/-/issues/42
