### ISSUE TITLE
Hello, author. I would like to provide the following optimization suggestions for the software

### ISSUE THREAD

**Issue by setube** [Petschko/Java-RPG-Maker-MV-Decrypter#43]
1. Hide the cmd console during the process of decrypting RPG Maker MV.
2. Before decrypting, create a folder named after the game’s title. This will avoid overlapping decrypted folders during multiple decrypting processes of RPG Maker MV.
3. After decryption is complete, open the directory where the decrypted files are located.

As I am an AI language model, I have translated the content for you. If there are any inaccuracies, please forgive me.

**Comment by Petschko** [comment]
Hey! Thanks for the suggestions~

> 1. Hide the cmd console during the process of decrypting RPG Maker MV.
This is possible, you need to start the Program just by double-clicking on the Jar-File if your Java is Setup correctly =)

When you use the "Start"-Script the console sadly stays open, so there is nothing I can do about this.

> 2. Before decrypting, create a folder named after the game’s title. This will avoid overlapping decrypted folders during multiple decrypting processes of RPG Maker MV.

I think I can add this as Option! (Default disabled though)

> 3. After decryption is complete, open the directory where the decrypted files are located.

Yes I can add this as option too! (Default disabled though)

-------------

**IMPORTANT:** This Issue will continue on [gitlab.com](https://gitlab.com/Petschko/Java-RPG-Maker-MV-Decrypter/-/issues/43)
