### ISSUE TITLE
Add Program Update Function

### ISSUE THREAD

**Issue by Petschko** [Petschko/Java-RPG-Maker-MV-Decrypter#8]
I want to add a Function that shows that there is a new Version. I think thats pretty important, if I add important new stuff, so that People know that
But I will also add an Option to disable it for those who don't want get notified (Should disable the checking as well)

Later: Also with 1-Click update if you are ready to update

**Comment by a2937** [comment]
For the record, if you ever want to do this; you would need to hook up an HTTP client and contact the GitHub API at the points listed [here](https://developer.github.com/v3/repos/releases/#get-the-latest-release)

**Comment by Petschko** [comment]
Cant tell if I want to add this, but I dont think I will use the Github API for that

**Comment by Petschko** [comment]
Added: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/commit/1ef737e2ffac9d0a3e8a02b70f3943afd60b72d4
